### ISSUE TITLE
jsstrip and omit semicolon in modern JavaScript

### ISSUE THREAD

**Issue by fjf2002** [splitbrain/php-jsstrip#1]
Modern JavaScript allows to omit semicolons.

Unfortunately, DokuWiki's jsstrip can't deal with that when compressing.

My chrome sometimes seems to expect at least one whitespace where previously a semicolon was mandatory.

But jsstrip eliminates that.

The following example fails in chrome (when compressed by jsstrip),  preferably at the lines ending in `)`.

```js
    function getInputByLabelText(name) {
        return document.evaluate(
            `//span[contains(text(),'${name}')]/following-sibling::input`,
            document.getElementsByTagName("form")[0],
            null,
            XPathResult.FIRST_ORDERED_NODE_TYPE
        ).singleNodeValue

    }

    fetch('/meh.php')
        .then(response => response.json())
        .then(json => {
            const input = getInputByLabelText('foo')

            if (input) {
                // fail for example here:
                const datalist = document.createElement("datalist")

                // more code here
            }
        });
```

**Comment by splitbrain** [comment]
This is clearly stated in the README.

**Comment by fjf2002** [comment]
@splitbrain Thanks for pointing that out. Is there any interest in extending jsstrip to support JavaScript code without semicolons? I could elaborate a bit.

**Comment by splitbrain** [comment]
TBH it's probably not worth it

* if you're looking for a library to use in a project, you're probably better off with something like tedious/JShrink
* if you're writing JS for DokuWiki you can simply add the semicolons
* if you add third party libraries to DokuWiki you can add pre-minified versions. let them end in .min.js and use DW's include mechanism - DokuWiki will not reminify them

**Comment by fjf2002** [comment]
OK, thanks. The second bullet applies to me.

My attempt for jsstrip would have been: Replace newlines by spaces, and do not eliminate these. This would have been enough, I think.
